### ISSUE TITLE
MsHackMan - My bot sends "right" action but Test Game I/O tells I didn't send anything

### ISSUE THREAD

**Issue by logisin** [riddlesio/issues#70] opened 2017-11-22 20:27 UTC
I have made a bot for the MsHackMan game using C++14 and Visual Studio 2017. When I ran the log of the game to my PC up to round 71 the bot sends the move "right" but Test Game log says that I haven't sent anything. Maybe there is a bug. Please help, I've send the code and the game.log.
[Project1.zip](https://github.com/riddlesio/issues/files/1497386/Project1.zip)

**Comment by JimVanEeden** [comment] 2017-11-23 07:52
This is most likely a bug in your bot. But it's hard for me to help you as I really don't know much about C++. Maybe you can ask on the forum of Ms. Hack-man and somebody can help you.

**Comment by tombsar** [comment] 2017-11-25 20:33
@logisin It looks to me as though your bot is crashing (segfault) during the processing of round 45. It seems Visited::setElementXY might be trying to access an element of a std::vector that doesn't exist, but I didn't take the time to investigate further.

@JimVanEeden This relates to something I was thinking about creating a new issue for. If the user's bot terminates for whatever reason, the engine seems to ignore it and keep going regardless. It would be nice if the match was forfeited at that point, and a useful error message printed to the log.

**Comment by nikovanmeurs** [comment] 2017-11-28 19:54
@tombsar sounds good, a separate issue on the topic is certainly welcome. I'll be closing this issue as it's not a bug in the platform or the engine.

**Closed by nikovanmeurs** 2017-11-28 19:54 UTC
Labels: invalid
