### ISSUE TITLE
LIGHT RIDERS - Upload fails and stuck on Compiling

### ISSUE THREAD

**Issue by RotemKariv** [riddlesio/issues#78] opened 2017-12-02 10:04 UTC
Hi,

I am trying to upload new bots to light riders game, but everytime I try it fails to upload, and in overview screen i can see all those uploads in a compliling loop.  

It happens even with the basic kit.

thanks for the help

**Comment by JimVanEeden** [comment] 2017-12-02 10:31
We're aware of the issue, somebody else posted as well. We're looking into it at the moment, but we're not exactly sure what's causing it.

**Comment by tombsar** [comment] 2017-12-06 01:32
Same thing is happening for me with Ms. Hack-Man

**Comment by tiramon** [comment] 2017-12-13 21:09
Currently happend 2 times on Ms.HackMan

**Comment by jltemple** [comment] 2017-12-13 22:56
Been going on for a few hours in Ms. Hack-Man 
![2017-12-13_17-55-40](https://user-images.githubusercontent.com/3419268/33966788-dc1613b6-e02e-11e7-8c2c-ceaa9d9da12e.png)

**Comment by tiramon** [comment] 2017-12-14 06:35
And again or maybe even more a still failing

Strange ... It says 'Your bot could not be uploaded' and after a refresh it appears in the Overview as a new revision and says 'Upload completed' and when i click the download button it looks like it was completly uploaded...

Also console output during 'failed upload'
![image](https://user-images.githubusercontent.com/642242/33978695-477f96f0-e0a1-11e7-8241-d6dd5ca0b23c.png)

**Comment by JimVanEeden** [comment] 2017-12-14 07:51
This problem is platform wide and also goes for challenges. I can explain a bit more about the problem maybe. When you upload a bot, a request is sent to the API that will create a new bot revision. The API then sends a request to the compiler with that bot revision so that the whole compile - test process is started. The problem is with RabbitMQ, a queue system that handles the request from the API to the compiler. RabbitMQ has lately been super unstable and occasionally jams, we're trying very hard to find the exact problem but it has been giving us headaches.

**Comment by JimVanEeden** [comment] 2018-02-19 14:40
Closing as we've fixed our stability issues.

**Closed by JimVanEeden** 2018-02-19 14:40 UTC
