### ISSUE TITLE
Opening links in a new tab breaks the site

### ISSUE THREAD

**Issue by melsonius** [riddlesio/issues#22] opened 2017-06-02 06:24 UTC
* Delete all cookies and local storage for *.riddles.io
* Go to starapple.riddles.io
* Click on log in, and enter valid credentials
* Click on Compete Now to go to the overview
* Open any Submission Logs or View Test Match link *in a new tab*
* Observe complete inability to load any pages on starapple.riddles.io (permanent "Loading Riddles.io" spinner)

**Comment by melsonius** [comment] 2017-06-02 06:27
The site seems to work fine as long as I don't open multiple tabs, but that makes me sad because I can't see both my output and the nice visualizer at the same time!  :)

**Comment by JimVanEeden** [comment] 2017-06-02 06:50
Personally I can't reproduce this, but some of they other guys _can_, so we'll have a look at it. It's definitely a bug though.

**Comment by asvyazin** [comment] 2017-06-02 08:24
I have the same problem. Also there are some javascript errors in the browser console:
```
Uncaught TypeError: Cannot read property '__reactInternalInstance$lvinwhgw51a' of null
    at Object.u [as getClosestInstanceFromNode] (/js/app.91eba2c8dbc07dea4012.js:4)
    at r (/js/app.91eba2c8dbc07dea4012.js:4)
    at i (/js/app.91eba2c8dbc07dea4012.js:4)
    at r.perform (/js/app.91eba2c8dbc07dea4012.js:4)
    at Object.batchedUpdates (/js/app.91eba2c8dbc07dea4012.js:4)
    at Object.i [as batchedUpdates] (/js/app.91eba2c8dbc07dea4012.js:4)
    at dispatchEvent (/js/app.91eba2c8dbc07dea4012.js:4)
    at HTMLImageElement.r (/js/app.91eba2c8dbc07dea4012.js:4)
/js/app.91eba2c8dbc07dea4012.js:4 Uncaught TypeError: Cannot read property '__reactInternalInstance$lvinwhgw51a' of null
    at Object.u [as getClosestInstanceFromNode] (/js/app.91eba2c8dbc07dea4012.js:4)
    at r (/js/app.91eba2c8dbc07dea4012.js:4)
    at i (/js/app.91eba2c8dbc07dea4012.js:4)
    at r.perform (/js/app.91eba2c8dbc07dea4012.js:4)
    at Object.batchedUpdates (/js/app.91eba2c8dbc07dea4012.js:4)
    at Object.i [as batchedUpdates] (/js/app.91eba2c8dbc07dea4012.js:4)
    at dispatchEvent (/js/app.91eba2c8dbc07dea4012.js:4)
    at HTMLImageElement.r (/js/app.91eba2c8dbc07dea4012.js:4)
```

**Comment by nikovanmeurs** [comment] 2017-06-02 09:24
The fix has been deployed just now. Please let us know if you're still experiencing this issue.

**Closed** 2017-06-02 13:46 UTC
